### ISSUE TITLE
搜图发送图片后报错

### ISSUE THREAD

**Issue by histion** [cpuopt/nonebot_plugin_imgexploration#16]
06-21 11:24:43 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_imgexploration) running complete
06-21 11:24:43 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Histion\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 53, in get_pic
    search = Imgexploration(
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 25, in __init__
    self.setFront(big_size=25, nomal_size=20, small_size=15)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 91, in setFront
    self.__font_b = ImageFont.truetype("HarmonyOS_Sans_SC_Regular", big_size)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Histion\Desktop\1\first\.venv\Lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by cpuopt** [comment]
没有安装字体

**Comment by histion** [comment]
> 没有安装字体

发这个issue之前安装了，重启后还是不行

**Comment by cpuopt** [comment]
看一下系统字体列表

**Comment by histion** [comment]
> 看一下系统字体列表

换了虚拟机上弄解决了
