### ISSUE TITLE
疑似的字体错误，但字体确实安装正确

### ISSUE THREAD

**Issue by NirvanaTGP** [cpuopt/nonebot_plugin_imgexploration#18]
使用搜图功能后
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "F:\Nahida\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "F:\Nahida\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "F:\Nahida\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "F:\Nahida\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\Nahida\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "F:\Nahida\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "F:\Nahida\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "F:\Nahida\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "F:\Nahida\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\Nahida\.venv\lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 53, in get_pic
    search = Imgexploration(
  File "F:\Nahida\.venv\lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 25, in __init__
    self.setFront(big_size=25, nomal_size=20, small_size=15)
  File "F:\Nahida\.venv\lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 91, in setFront
    self.__font_b = ImageFont.truetype("HarmonyOS_Sans_SC_Regular", big_size)
  File "F:\Nahida\.venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "F:\Nahida\.venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "F:\Nahida\.venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by cpuopt** [comment]
### 1.请注意需要安装的字体文件名称为：
```
HarmonyOS_Sans_SC_Regular.ttf  
HarmonyOS_Sans_SC_Bold.ttf  
HarmonyOS_Sans_SC_Light.ttf
```
### 2.如果系统有多个账户在使用，安装时右键选择“为所有用户安装”
