### ISSUE TITLE
使用搜图功能后出现

### ISSUE THREAD

**Issue by keivnhousid** [cpuopt/nonebot_plugin_imgexploration#21]
01-02 21:46:36 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration, lineno=37) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 53, in get_pic
    search = Imgexploration(
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 25, in __init__
    self.setFront(big_size=25, nomal_size=20, small_size=15)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 91, in setFront
    self.__font_b = ImageFont.truetype("HarmonyOS_Sans_SC_Regular", big_size)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\PIL\ImageFont.py", line 819, in truetype
    return freetype(font)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\PIL\ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\hou33\Desktop\lostark-bot\lostark\.venv\Lib\site-packages\PIL\ImageFont.py", line 245, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by cpuopt** [comment]
字体安装问题
