### ISSUE TITLE
插件加载时报错

### ISSUE THREAD

**Issue by y0509** [cpuopt/nonebot_plugin_imgexploration#22]
(robot) PS C:\Users\ReiLove\Desktop\bot\robot> nb run --reload
使用 Python: C:\Users\ReiLove\Desktop\bot\robot\.venv\Scripts\python.exe
启动重载监视，当前进程 [24060].
03-23 12:03:54 [SUCCESS] nonebot | NoneBot is initializing...
03-23 12:03:54 [INFO] nonebot | Current Env: prod
03-23 12:03:55 [ERROR] nonebot | Failed to import "nonebot_plugin_guild_patch"
Traceback (most recent call last):
  File "C:\Users\ReiLove\Desktop\bot\robot\bot.py", line 8, in <module>
    nonebot.load_plugin('nonebot_plugin_guild_patch')
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\ReiLove\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 6, in <module>
    from .models import (
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 50, in GuildMessageEvent
    @root_validator(pre=False)
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.6/u/root-validator-pre-skip
03-23 12:03:55 [ERROR] nonebot | Failed to import "nonebot_plugin_guild_patch"
Traceback (most recent call last):
  File "C:\Users\ReiLove\Desktop\bot\robot\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\ReiLove\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 10, in <module>
    require("nonebot_plugin_guild_patch")
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 173, in require
    plugin = manager.load_plugin(name)
> File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\ReiLove\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 6, in <module>
    from .models import (
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 50, in GuildMessageEvent
    @root_validator(pre=False)
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.6/u/root-validator-pre-skip
03-23 12:03:55 [ERROR] nonebot | Failed to import "nonebot_plugin_imgexploration"
Traceback (most recent call last):
  File "C:\Users\ReiLove\Desktop\bot\robot\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\ReiLove\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 10, in <module>
    require("nonebot_plugin_guild_patch")
  File "C:\Users\ReiLove\Desktop\bot\robot\.venv\lib\site-packages\nonebot\plugin\load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_guild_patch"!
03-23 12:03:55 [SUCCESS] nonebot | Running NoneBot...
03-23 12:03:55 [INFO] uvicorn | Started server process [20656]
03-23 12:03:55 [INFO] uvicorn | Waiting for application startup.
03-23 12:03:55 [INFO] uvicorn | Application startup complete.
03-23 12:03:55 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
多次重新安装插件仍无法解决

**Comment by cpuopt** [comment]
是nonebot_plugin_guild_patch加载失败导致的。
问题在报错堆栈中已经写出
`pydantic.errors.PydanticUserError: If you use @root_validator with pre=False (the default) you MUST specify skip_on_failure=True. Note that @root_validator is deprecated and should be replaced with @model_validator.`

临时解决办法：降级pydantic
在nonebot的环境中执行`pip install pydantic==1.10.9`
实测可解决问题

**Comment by y0509** [comment]
已解决，感谢
