### ISSUE TITLE
Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.

### ISSUE THREAD

**Issue by lihaoze123** [cpuopt/nonebot_plugin_imgexploration#4]
The plugin crashes after sending image.

```
01-08 21:32:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_imgexploration) running complete
01-08 21:32:17 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):

  File "/udisk/bot/.venv/lib/python3.9/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task cancelling name='Task-3513' coro=<Imgexploration.doSearch() running at /udisk/bot/.venv/lib/python3.9/site-packages/non...
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
    raise
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
    self.run_forever()
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
    self._run(mode)
  File "uvloop/loop.pyx", line 518, in uvloop.loop.Loop._run
    raise RuntimeError('this event loop is already running.')

RuntimeError: this event loop is already running.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/udisk/bot/.venv/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0xffff80e38dc0>
           └ <ClickAliasedGroup main>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0xffff810321f0>
         │    └ <function MultiCommand.invoke at 0xffff80dbcdc0>
         └ <ClickAliasedGroup main>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0xffff81032d30>
           │               │       │       └ <function Command.invoke at 0xffff80dbc8b0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0xffff81032d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0xffff81031d30>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0xffff81032d30>
           │   │      │    └ <function run at 0xffff7e35d3a0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0xffff80e38670>
           └ <click.core.Context object at 0xffff81032d30>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0xffff7e349ee0>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0xffff7f5ddaf0>
    └ <module 'nonebot' from '/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/__init__.py'>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0xffff7faf3550>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0xffff7e00a5e0>
    └ <module 'uvicorn' from '/udisk/bot/.venv/lib/python3.9/site-packages/uvicorn/__init__.py'>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0xffff7e00a9d0>
    └ <uvicorn.server.Server object at 0xffff64346460>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0xffff7e00aa60>
           │       │   └ <uvicorn.server.Server object at 0xffff64346460>
           │       └ <function _patch_asyncio.<locals>.run at 0xffff647f1310>
           └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /udisk/bot/.venv/lib/python3.9/site-packages/uvicorn/server.py:80...
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
    └ <Task pending name='Task-3480' coro=<_check_matcher() running at /udisk/bot/.venv/lib/python3.9/site-packages/nonebot/message...
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
    │         │     └ None
    │         └ <Task pending name='Task-3480' coro=<_check_matcher() running at /udisk/bot/.venv/lib/python3.9/site-packages/nonebot/message...
    └ <function Task.__step at 0xffff8010e550>
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object _check_matcher at 0xffff58309240>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0xffff642e5d30>: <Task finished name='Task-3502' coro=<Matcher.got.<locals>._k...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0xffff582a12e0>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │            │        │    └ PrivateMessageEvent(time=1673184736, self_id=2653148271, post_type='message', sub_type='friend', user_id=259****810, message_...
          │            │        └ Bot(type='OneBot V11', self_id='2653148271')
          │            └ Matcher(type='message', module=nonebot_plugin_imgexploration)
          └ <function _run_matcher at 0xffff7e282550>
> File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0xffff642e5d30>: <Task finished name='Task-3502' coro=<Matcher.got.<locals>._k...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0xffff582a12e0>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │       │   │    └ PrivateMessageEvent(time=1673184736, self_id=2653148271, post_type='message', sub_type='friend', user_id=259****810, message_...
          │       │   └ Bot(type='OneBot V11', self_id='2653148271')
          │       └ <function Matcher.run at 0xffff80efd310>
          └ Matcher(type='message', module=nonebot_plugin_imgexploration)
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0xffff642e5d30>: <Task finished name='Task-3502' coro=<Matcher.got.<locals>._k...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0xffff582a12e0>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │    │          │    └ PrivateMessageEvent(time=1673184736, self_id=2653148271, post_type='message', sub_type='friend', user_id=259****810, message_...
          │    │          └ Bot(type='OneBot V11', self_id='2653148271')
          │    └ <function Matcher.simple_run at 0xffff80efd3a0>
          └ Matcher(type='message', module=nonebot_plugin_imgexploration)
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=get_pic, parameterless=(Depends(Dependent(call=_key_getter)),))
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='2653148271'), 'event': PrivateMessageEvent(time=1673184736, self_id=2653148271, post_...
                 │    │             │         │    │    └ <function get_pic at 0xffff7e1668b0>
                 │    │             │         │    └ Dependent(call=get_pic, parameterless=(Depends(Dependent(call=_key_getter)),))
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0xffff81016af0>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot_plugin_imgexploration/__init__.py", line 51, in get_pic
    search.run()
    │      └ <function Imgexploration.run at 0xffff642e5c10>
    └ <nonebot_plugin_imgexploration.imgexploration.Imgexploration object at 0xffff582a1250>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nonebot_plugin_imgexploration/imgexploration.py", line 448, in run
    asyncio.run(self.doSearch())
    │       │   │    └ <function Imgexploration.doSearch at 0xffff642e5b80>
    │       │   └ <nonebot_plugin_imgexploration.imgexploration.Imgexploration object at 0xffff582a1250>
    │       └ <function _patch_asyncio.<locals>.run at 0xffff647f1310>
    └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
  File "/udisk/bot/.venv/lib/python3.9/site-packages/nest_asyncio.py", line 40, in run
    loop.run_until_complete(task)
    │    │                  └ <Task cancelling name='Task-3513' coro=<Imgexploration.doSearch() running at /udisk/bot/.venv/lib/python3.9/site-packages/non...
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
    raise
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
    self.run_forever()
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
    self._run(mode)
  File "uvloop/loop.pyx", line 518, in uvloop.loop.Loop._run
    raise RuntimeError('this event loop is already running.')

RuntimeError: this event loop is already running.
```

**Comment by cpuopt** [comment]
使用nest_asyncio之后，我没有出现过这个问题
不过你可以尝试将`imgexploration.py` 12 行的
```
nest_asyncio.apply()
```
改到447行run方法中
```
def run(self):
     nest_asyncio.apply()
     asyncio.run(self.doSearch())
```
python 3.10.8
nest-asyncio 1.5.6

**Comment by lihaoze123** [comment]
> 使用nest_asyncio之后，我没有出现过这个问题 不过你可以尝试将`imgexploration.py` 12 行的
> 
> ```
> nest_asyncio.apply()
> ```
> 
> 改到447行run方法中
> 
> ```
> def run(self):
>      nest_asyncio.apply()
>      asyncio.run(self.doSearch())
> ```
> 
> python 3.10.8 nest-asyncio 1.5.6

依旧无济于事，依据 StackOverflow 的回答[^1]，反而是原本的位置是正确的，但是更改这行代码的位置并没有什么帮助，反而导致了另外的问题
```
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```
[^1]: https://stackoverflow.com/a/67228201

**Comment by lihaoze123** [comment]
删除了 `uvloop` 库之后，问题得到解决。
![image](https://user-images.githubusercontent.com/35329574/211253704-36f3a0d9-0e32-4da6-abdd-6f12a3fb94ae.png)

**Comment by cpuopt** [comment]
> 删除了 `uvloop` 库之后，问题得到解决。 ![image](https://user-images.githubusercontent.com/35329574/211253704-36f3a0d9-0e32-4da6-abdd-6f12a3fb94ae.png)

我刚刚修改了代码，去除了嵌套事件循环，不再需要nest_asyncio，可以继续使用uvloop

**Comment by lihaoze123** [comment]
> > 删除了 `uvloop` 库之后，问题得到解决。 ![image](https://user-images.githubusercontent.com/35329574/211253704-36f3a0d9-0e32-4da6-abdd-6f12a3fb94ae.png)
> 
> 我刚刚修改了代码，去除了嵌套事件循环，不再需要nest_asyncio，可以继续使用uvloop

thx
