### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by HAKURELING** [cpuopt/nonebot_plugin_imgexploration#5]
01-30 09:48:39 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-30 09:48:39 [SUCCESS] nonebot | Succeeded to import "echo"
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_heweather"
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_pixivrank_search"
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_guild_patch"
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_abbrreply"
01-30 09:48:40 [DEBUG] nonebot_plugin_trace_moe | 2
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_trace_moe"
01-30 09:48:40 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
01-30 09:48:40 [ERROR] nonebot | Failed to import "nonebot_plugin_imgexploration"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/LING/./bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_imgexploration/__init__.py", line 10, in <module>
    from .imgexploration import Imgexploration
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_imgexploration/imgexploration.py", line 13, in <module>
    class Imgexploration:
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_imgexploration/imgexploration.py", line 95, in Imgexploration
    async def ImageBatchDownload(urls: list, client: httpx.AsyncClient) -> list[bytes]:
TypeError: 'type' object is not subscriptable
![image](https://user-images.githubusercontent.com/63252182/215445106-eedde48f-0fef-4d6c-a5ef-78966b5cb005.png)

**Comment by cpuopt** [comment]
考虑是uvicorn和uvloop导致的兼容问题，插件使用原生asyncio，卸载uvicorn和uvloop后再尝试

**Comment by HAKURELING** [comment]
uvicorn卸载之后直接没法启动了🤣

**Comment by HAKURELING** [comment]
卸载uvicorn之后直接没办法启动bot了🤔

**Comment by cpuopt** [comment]
我后来一直用的环境是python3.11，nb-cli1.0.0以上版本

**Comment by HAKURELING** [comment]
那我回头升级一下Python环境再试试😂，感谢感谢
