### ISSUE TITLE
发送图片后报错#OSError: cannot open resource

### ISSUE THREAD

**Issue by WeiLanKing** [cpuopt/nonebot_plugin_imgexploration#6]
`[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot_plugin_imgexploration\__init__.py", line 47, in get_pic
    search = Imgexploration(pic_url=pic_url, client=client,proxy=f"http://127.0.0.1:{proxy_port}", saucenao_apikey=saucenao_apikey)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 25, in __init__
    self.setFront(big_size=25, nomal_size=20, small_size=15)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\nonebot_plugin_imgexploration\imgexploration.py", line 90, in setFront
    self.__font_b = ImageFont.truetype("HarmonyOS_Sans_SC_Regular", big_size)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\PIL\ImageFont.py", line 1008, in truetype
    return freetype(font)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\PIL\ImageFont.py", line 1005, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\1\AppData\Local\pypoetry\Cache\virtualenvs\webot-bWFYmPaM-py3.10\lib\site-packages\PIL\ImageFont.py", line 255, in __init__
    self.font = core.getfont(
OSError: cannot open resource`

**Comment by cpuopt** [comment]
### 2.需要字体    
```
HarmonyOS_Sans_SC_Regular.ttf  
HarmonyOS_Sans_SC_Bold.ttf  
HarmonyOS_Sans_SC_Light.ttf
```
https://developer.harmonyos.com/cn/docs/design/des-guides/font-0000001157868583   
安装到系统字体即可

**Comment by WeiLanKing** [comment]
请问我用poetry run安装插件的，这个系统文字好像无法使用到，这个字体如何安装到poetry，请教一下。

**Comment by cpuopt** [comment]
https://github.com/cpuopt/nonebot_plugin_imgexploration/blob/main/nonebot_plugin_imgexploration/imgexploration.py#L90-L92
这三行里的字体名称改成字体文件路径就可以了

**Comment by WeiLanKing** [comment]
```
self.__font_b = ImageFont.truetype("C:/Users/1/AppData/Local/Microsoft/Windows/Fonts", big_size)
self.__font_n = ImageFont.truetype("C:/Users/1/AppData/Local/Microsoft/Windows/Fonts", nomal_size)
self.__font_s = ImageFont.truetype("C:/Users/1/AppData/Local/Microsoft/Windows/Fonts", small_size)
```

这样？还是同样的报错

**Comment by cpuopt** [comment]
安装到系统内：
首先要 **下载字体**
https://developer.harmonyos.com/cn/docs/design/des-guides/font-0000001157868583 ，解压，找到`HarmonyOS_Sans_SC_Regular.ttf`、`HarmonyOS_Sans_SC_Bold.ttf`、`HarmonyOS_Sans_SC_Light.ttf` 三个字体文件，右键安装
不想安装字体：
```
self.__font_b = ImageFont.truetype("字体文件相对路径或绝对路径/HarmonyOS_Sans_SC_Regular.ttf", big_size)
self.__font_n = ImageFont.truetype("字体文件相对路径或绝对路径/HarmonyOS_Sans_SC_Bold.ttf", nomal_size)
self.__font_s = ImageFont.truetype("字体文件相对路径或绝对路径/HarmonyOS_Sans_SC_Light.ttf", small_size)
```
