### ISSUE TITLE
UnboundLocalError: local variable 'result_li' referenced before assignment

### ISSUE THREAD

**Issue by RokasUrbelis** [cpuopt/nonebot_plugin_imgexploration#7]
![image](https://user-images.githubusercontent.com/48517501/218276288-cd846435-211d-425e-85cf-14378e24f55d.png)
02-12 02:58:47 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/opt/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/opt/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/__init__.py", line 49, in get_pic
    await search.doSearch()
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/imgexploration.py", line 411, in doSearch
    self.__result_info = (await task_saucenao) + (await task_ascii2d) + (await task_google) + (await task_yandex)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/imgexploration.py", line 355, in __ascii2d_build_result
    logger.success(f"ascii2d result:{len(result_li)}")
UnboundLocalError: local variable 'result_li' referenced before assignment
02-12 02:58:47 [ERROR] nonebot_plugin_imgexploration | [Errno -2] Name or service not known
02-12 02:58:47 [SUCCESS] nonebot_plugin_imgexploration | google result:0
02-12 02:58:47 [ERROR] nonebot_plugin_imgexploration | [Errno -2] Name or service not known

第二个问题，proxy变量应该不是必填项吧，我本地走openwrt，不需要在系统上单独设置proxy

**Comment by cpuopt** [comment]
那肯定是不填不行

**Comment by cpuopt** [comment]
修改了一个无代理的版本
https://github.com/cpuopt/nonebot_plugin_imgexploration/tree/no-proxies/nonebot_plugin_imgexploration
替换这两个py文件就可以了

**Comment by RokasUrbelis** [comment]
替换两个文件后，代理问题解决了，这个报错仍然还在：
![image](https://user-images.githubusercontent.com/48517501/218331523-eb0faefb-16af-4c31-ba86-34f2490c8f6b.png)
02-13 03:03:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/opt/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/opt/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/__init__.py", line 48, in get_pic
    await search.doSearch()
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/imgexploration.py", line 409, in doSearch
    self.__result_info = (await task_saucenao) + (await task_ascii2d) + (await task_google) + (await task_yandex)
  File "/opt/first/.venv/lib/python3.10/site-packages/nonebot_plugin_imgexploration/imgexploration.py", line 353, in __ascii2d_build_result
    logger.success(f"ascii2d result:{len(result_li)}")
UnboundLocalError: local variable 'result_li' referenced before assignment

**Comment by RokasUrbelis** [comment]
而且每次都出现几个ERROR：
![image](https://user-images.githubusercontent.com/48517501/218332371-a5104272-dc91-4de7-8622-2748321f189f.png)

Drawing 搜出来的东西差距太大
![image](https://user-images.githubusercontent.com/48517501/218332243-810faa45-d22b-4d02-925e-032901d20d0c.png)
![image](https://user-images.githubusercontent.com/48517501/218332278-60f05137-3604-442c-84eb-91eed0f32d41.png)

**Comment by cpuopt** [comment]
ERROR和那个报错是网络问题，梯子共用的人太多，撞了网站的速率限制
比如我这个梯子是没问题的
![img](https://p.inari.site/usr/369/63ea38103f3ba.png)
![img](https://p.inari.site/usr/369/63ea3578134bc.jpg)
saucenao和ascii2d是用来搜动漫插画的，识别不了其他图片

**Comment by cpuopt** [comment]
刚刚更新了0.2.4
解决了result_li未定义问题 (logger的error是网络问题，只能换节点或换梯子解决)
不使用代理，不写配置项proxy_port或留空就可以，用pip更新或nb plugin重装插件就行

**Comment by RokasUrbelis** [comment]
✅已解决。
